<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>LogoVMS.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="LogoVMS.ico" />
    <ProjectReference Include="D:\KHACH_HANG\SUNSTEEL\Source_Code\VmsDevice\VmsDevice\VmsDevice.csproj" />
  </ItemGroup>

</Project>
